
logging:
  level:
    org.springframework: WARN
---
spring:
  jpa:
    database: oracle
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:oracle:thin:@ora14.informatik.haw-hamburg.de:1521:inf14
    driverClassName:  oracle.jdbc.OracleDriver
    username: acx394
    password:
  h2:
    console:
      enabled: true
  mail:
    host: ora14.informatik.haw-hamburg.de
    port: 1521
    username: fake
    password: fake
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true